### ISSUE TITLE
Searches fail with key error

### ISSUE THREAD

**Issue by j6k4m8** [JonShepChen/SpotipyTUI#4]
```
Traceback (most recent call last):
  File "/usr/local/bin/spotipy-tui", line 7, in <module>
    from spotipy_tui.app import run
  File "/usr/local/lib/python3.6/site-packages/spotipy_tui/app.py", line 103, in <module>
    curses.wrapper(run_loop)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/spotipy_tui/app.py", line 68, in run_loop
    command_dict.get(char_input)()
  File "/usr/local/lib/python3.6/site-packages/spotipy_tui/command.py", line 136, in search_content
    self.track_list = requester.execute_search(user_search, self.country_id, self.track_window.getmaxyx()[0]-3)
  File "/usr/local/lib/python3.6/site-packages/spotipy_tui/requester.py", line 5, in execute_search
    track_list = parse_search_results(raw_results)
  File "/usr/local/lib/python3.6/site-packages/spotipy_tui/requester.py", line 21, in parse_search_results
    for index, item in enumerate(target_json['tracks']['items']):
KeyError: 'tracks'
```

Looks like the API has changed? (btw, great project!)

**Comment by JoChaw** [comment]
Thanks for bringing up the issue! 

I need to bring this project back from the dead, haha. 

But yeah, through some quick searches it seems like accessing any of Spotify's API endpoints now requires access tokens whereas previously it was only required for accessing more user-specific data, which is kind of a drag. 

Besides updating the code, it seems like the users themselves would have to put in a little extra work in generating their own tokens through Spotify and insert it into the application before requests can be made. 

I'll see if I can find some time to look into this in-depth and code out a solution. 
Thanks for the heads up!
